describe('End to end ', function () {
  beforeEach(function () {
    cy.request('POST', 'localhost/api/testing/reset')
    cy.request('POST', 'localhost/api/register', { username: 'testuser', password: 'testpassword' })
    cy.clearLocalStorage()
    cy.login({ username: 'testuser', password: 'testpassword' })
    cy.visit('localhost')

    cy.addExercises()
  })
  it('User can add a workout and then look at exercise history', function () {
    cy.contains('Workouts').click()
    cy.contains('Add a new workout').click()
    cy.get('#date').type('2020-04-20')
    cy.get('#exerciselist').select('Squat')
    cy.get('#sets').type('3')
    cy.get('#reps').type('10')
    cy.get('#weight').type('80')
    cy.get('#add-exercise-button').click()
    cy.get('#submit-workout').click()
    cy.visit('localhost/exercise')
    cy.contains('Squat').click()
    cy.contains('Squat')
    cy.get('.recharts-surface')
    cy.contains('About weightValue')
  })
  it('Non-admin can suggest exercise, that is accepted and is then visible', function () {
    cy.admin({ username: 'testuser' })
    cy.contains('Logout').click()
    cy.request('POST', 'localhost/api/register', { username: 'nonadmin', password: 'nonadminpassword' })
    cy.login({ username: 'nonadmin', password: 'nonadminpassword' })
    cy.visit('localhost/exercise')
    cy.contains('Add a new exercise').click()
    cy.get('#name').type('Kegel swing')
    cy.get('#weight').click()
    cy.get('#submitExercise').click()
    cy.get('#message-container-visible-success').click()
    cy.contains('Logout').click()
    cy.login({ username: 'testuser', password: 'testpassword' })
    cy.visit('localhost/exercise')
    cy.get('#accept-Kegelswing').click()
    cy.contains('Exercise accepted').click()
    cy.contains('Logout').click()
    cy.login({ username: 'nonadmin', password: 'nonadminpassword' })
    cy.visit('localhost/exercise')
    cy.contains('Kegel swing')
  })
})