describe('Workout ', function () {
  beforeEach(function () {
    cy.request('POST', 'localhost/api/testing/reset')
    cy.request('POST', 'localhost/api/register', {username: 'testuser', password: 'testpassword'})
    cy.clearLocalStorage()
    cy.login({username: 'testuser', password: 'testpassword'})
    cy.visit('localhost')

    cy.addExercises()
  })
  it('Logged in users can add new workouts', function() {
    cy.contains('Workouts').click()
    cy.contains('Add a new workout').click()
    cy.get('#date').type('2020-04-20')
    cy.get('#exerciselist').select('Squat')
    cy.get('#sets').type('3')
    cy.get('#reps').type('10')
    cy.get('#weight').type('80')
    cy.get('#add-exercise-button').click()
    cy.get('#exerciselist').select('Running')
    cy.get('#distance').type('10000')
    cy.get('#add-exercise-button').click()
    cy.get('#submit-workout').click()
    cy.contains('New workout created succesfully')
  })
  it('User is notified if adding a workout fails', function() {
    cy.visit('localhost/workout')
    cy.contains('Add a new workout').click()
    cy.get('#date').type('2020-04-20')
    cy.get('#submit-workout').click()
    cy.contains('No exercises added to the workout')
  })
  it('Logged in users can view previous workouts', function() {
    cy.addWorkouts()
    cy.visit('localhost/workout')
    cy.contains('Previous workouts')
    cy.contains('2001-09-11').click()
    cy.contains('Squat')
    cy.contains('2000-10-10').click()
    cy.contains('Running')
  })
})