version: '3.5'
services:
  backend:
    environment:
      - JWT_SECRET
      - MONGO_PASS
      - MONGO_USER
    command: npm run start:test
  frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile-ci
    command: npm start
