version: '3.5'
services:
  backend:
    build:
      context: ./server/
      target: development
    command: npm start
    ports: 
      - "8000:8000"
    volumes:
      - ./server/:/app

  nginx:
    image: nginx
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./client/
      target: development
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app
    depends_on:
      - backend