name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hack .env file
      run: touch ./server/.env
    - name: build server and client for node_modules
      run: cd server && npm install && cd ../client && npm install && cd ..
    - name: Build the Docker compose stack
      run: docker-compose up -d
      env:
        JWT_SECRET: $ {{ secrets.JWT_SECRET }}
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs jafa_backend_1 || docker logs jafa_frontend_1
    - name: Run lint for backend
      run: docker exec jafa_backend_1 npm run lint
    - name: Run lint for frontend
      run: docker exec jafa_frontend_1 npm run lint
