name: Docker Image CI

on:
  push:
    branches:
    - master
    - '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: build server and client for node_modules
      run: cd server && npm install && cd ../client && npm install && cd ..
    - name: Build the Docker compose stack
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASS: ${{ secrets.MONGO_PASS }}
      run: docker-compose -f docker-compose.yml -f docker-compose-ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs jafa_backend_1 || docker logs jafa_frontend_1
    - name: Run lint for backend
      run: docker exec jafa_backend_1 npm run lint
    - name: Run lint for frontend
      run: docker exec jafa_frontend_1 npm run lint
    - name: Run unit tests for backend
      run: docker exec jafa_backend_1 npm test
    - name: Run cypress tests
      run: cd client && npm rebuild node-sass && npm run cy:test
